version: "3"
services:
  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ../data/redis:/data

  api:
    image: bla
    restart: always
    links:
      - redis
    ports:
      - 8080:3000